added youtubedl-exec

diff --git a/termux-file-editor b/termux-file-editor
--- a/termux-file-editor
+++ b/termux-file-editor
@@ -1,6 +1,7 @@
 #!/data/data/com.termux/files/usr/bin/bash
 
-set -x
+set -e -u
+#set -x
 
 FILE="$1"
 
@@ -14,17 +15,19 @@ termux-url-opener() {
 	/data/data/com.termux/files/home/bin/termux-url-opener "$URL"
 }
 
-main() {
+while true
+do
 	echo "What should I do with this file?"
 	echo "u) grab the url and call termux-url-opener"
 	echo "c) custom command"
-	echo "x) nothing"
+	echo "x) exit"
 	
-	read CHOICE
+	read -p "Enter your choice: " CHOICE
 	case "$CHOICE" in
 		u)
 			termux-url-opener
-			rm "$FILE"
+			rm -i "$FILE"
+			exit
 			;;
 		c)
 			read -p "Enter your command: " CMD
@@ -35,10 +38,7 @@ main() {
 			exit
 			;;
 		*)
-			echo "Invalid command! Try again."
-			main
+			echo "Invalid choice! Try again."
 			;;
 	esac
-}
-
-main
+done
diff --git a/termux-url-opener b/termux-url-opener
--- a/termux-url-opener
+++ b/termux-url-opener
@@ -1,55 +1,48 @@
 #!/data/data/com.termux/files/usr/bin/bash
 
-set -x
+set -e -u
+#set -x
 
-url="$1"
+URL="$1"
 
 quit() {
 	echo "bye 👋"
 	exit
 }
 
-#main() {
-	while true
-	do
-		echo "What should I do with "$url"?"
-		echo "y) download youtube video"
-		echo "a) play youtube audio"
-		echo "g) download as gif"
-		echo "d) download as file" 
-		echo "x) exit"
-		
-		read CHOICE
-		case "$CHOICE" in
-			y)
-				while true
-				do
-					read -p "Options? (x to exit) " OPTION
-					if [ "$OPTION" == "x" ]
-					then
-						quit
-					fi
-					youtube-dl $OPTION "$url"
-				done
-				;;
-			a)
-				mpsyt playurl "$url"
-				;;
-			g)
-				echo "NOT YET IMPLEMENTED"
-				;;
-		    d)
-				axel -o "~/storage/downloads/" "$url"
-				wget $url
-				;;
-		    x)
-				quit
-				;; 
-			*)
-				echo "invalid choice. Try again."
-				;;
-		esac
-	done
-#}
+while true
+do
+	echo "What should I do with "$URL"?"
+	echo "y) download youtube video"
+	echo "a) play youtube audio"
+	echo "d) download as file"
+	echo "x) nothing"
 
-#main
+	read -p "Enter your choice: " CHOICE
+	case "$CHOICE" in
+		y)
+			while true
+			do
+				read -p "Options? (x to exit) " OPTION
+				if [ "$OPTION" == "x" ]
+				then
+					quit
+				fi
+				youtube-dl $OPTION "$URL"
+			done
+			;;
+		a)
+			mpsyt playurl "$URL"
+			;;
+	    d)
+			axel -o "/storage/emulated/0/Download" "$URL"
+			;;
+	    x)
+			quit
+			;;
+		*)
+			echo "invalid choice. Try again."
+			;;
+	esac
+done
+
